aziontech/bundler

lib/presets/custom/angular/deliver/prebuild.js
lib/presets/custom/vue/deliver/prebuild.js

Fix in Angular preset prebuild, package manager compatibility.
This is because npm interprets arguments passed directly after the script as options for npm itself, not the script itself.
I performed tests with yarn, npm and pnpm managers.

fix: npm interprets arguments

---

examples/angular-static/package.json

Removing a dev dependency that was accidentally added in the angular static example.

chore: remove dev dependency

---

.github/workflows/minor.yml
examples/angular-static/package.json
lib/build/bundlers/webpack/webpack.config.js
lib/build/dispatcher/dispatcher.js
lib/platform/actions/core/auth.actions.js
lib/platform/actions/core/propagation.actions.js
lib/platform/actions/core/storage.actions.js
lib/utils/getAbsoluteLibDirPath/getAbsoluteLibDirPath.utils.js
lib/utils/getPresetsList/getPresetsList.utils.js
package.json

These changes run vulkan on the Windows operating system, working with filesystems in the correct way that the system supports.
We will no longer need to use the open dependency of the package.json file, we will use exec for the task, as open does not execute the file as soon as the deploy is ready.
- #### presets ls
- #### prebuild
- #### build
When running the deploy we have a problem with the core, as it is not able to read/find the files in the default url of the windows system, we will make some adjustments in the webpack, and in the core of the project, when completing the deploy and authentication process we found some errors that windows OS users.

[ISSUE-62] Windows Compatibility

---

.gitignore
examples/simple-js-esm/main.js
lib/commands/init.commands.js
lib/constants/messages/global.messages.js
lib/env/server.env.js
lib/env/vulcan.env.js
lib/utils/exec/exec.utils.js

In this release, we've enhanced the exec function in #utils for better management of 'exit' and 'close' events, while also introducing a streamlined .vulcan file that replaces the older .vulcan.env file, now being generated during both the build and init command processes to store preset information, thus simplifying the workflow by eliminating the need for redundant preset specifications in the [Azion-CLI](https://github.com/aziontech/azion-cli).

Release 1.6.0

---

lib/build/bundlers/esbuild/index.js
lib/build/bundlers/webpack/index.js
lib/build/dispatcher/dispatcher.js
lib/commands/build.commands.js
lib/env/vulcan.env.js

This PR introduces the possibility of creating a file called "vulcan.config.js" in the project so that it is possible to make build configurations directly in the project without the need to change presets.
It also introduces the _memoryFS_ object for in-memory fs usage (temporary solution):
- injectionDirs: array of strings indicating the directories that contain the files to be injected into memory.
- removePathPrefix: string with the prefix to be removed from the paths mapped for use in fs (e.g. in the case of vtex you need to remove .faststore).

feat: vulcan.config.js

---

lib/build/bundlers/esbuild/index.js
lib/build/bundlers/webpack/index.js
lib/build/dispatcher/dispatcher.js
lib/build/polyfills/node/fs.js
lib/build/polyfills/node/globals/process.js
lib/build/polyfills/node/module.js
lib/presets/custom/next/compute/config.js
lib/utils/index.js
lib/utils/injectFilesInMem/index.js
lib/utils/injectFilesInMem/injectFilesInMem.utils.js

This PR adds in memory file system feature.
During the build process (based on config) vulcan will read all specified directories and map the files. After this the build process will inject this mapping to a global var. 
The fs node module will get infos from this in memory mapping. 
You can test this in a next compute project.
In your project root create `vulcan.config.js` file to use this feature. The file must be like this:
```
module.exports = {
memoryFS: {
injectionDirs: ['.faststore/@generated/graphql'],
removePathPrefix: '.faststore/',
}
};
```
After this, run build and dev commands.
```
vulcan build --preset next --mode compute
vulcan dev
```

feat: In Memory File System

---

.gitignore
.npmignore
.prettierignore
docker-compose.yml
examples/simple-js-esm/main.js
package.json
tests/e2e/angular-static.test.js
tests/e2e/astro-static.test.js
tests/e2e/simple-js-esm.test.js
tests/scripts/destroy-e2e-env.sh
tests/scripts/setup-e2e-env.sh
tests/scripts/start-e2e-env.sh
tests/scripts/stop-e2e-env.sh
tests/utils/docker-env-actions.js
tests/utils/project-initializer.js
tests/utils/project-stop.js
verdaccio/config/config.yaml
yarn.lock

Create initial structure to e2e tests.
This PR includes:
- Create docker env with:
- A node container to simulate vulcan build, publish and use (azion cli like) in a clean env;
- A verdaccio container to simulate the npmjs registry.
- Scripts to help in e2e env management;
- Add supertest to simplify e2e tests (api, assets, ...);
- Add puppeteer to crawl pages (simplify SPA pages final result check - after hydration process );
- Example projects tests: astro, angular and javascript;
run in terminal 
```
yarn test:e2e
```
- `yarn test:e2e`: start docker env, run all e2e tests and stop docker env;
- `yarn e2e:start`: start docker env;
- `yarn e2e:start`: stop docker env;
- `yarn e2e:destroy`: delete docker env;
Run in terminal
```
yarn e2e:start
npx jest tests/e2e/FILE_NAME
yarn e2e:stop …
```

E2E tests - initial structure

---

lib/presets/custom/astro/deliver/prebuild.js
lib/utils/generateManifest/generateManifest.utils.js
lib/utils/generateManifest/index.js
lib/utils/index.js

The function must receive 3 arguments:
* @param {string} route - the route to be used,  or all represented by '*'
* @param {string} filePath - the file path for the route, or all represented by '*'
* @param {string} mode - The mode of the operation, either 'compute', 'deliver', or both represented by '*'.
*/

feat: generate manifest (initial structure)

---

.eslintignore
.prettierignore
CODEOWNERS
lib/build/bundlers/polyfills/node/fs.js

Fixing the fs polyfill when readdirsync and path == /, in this case the worker goes into a loop and crashes the process.

fix: loop in fs polyfill when readdirSync and path /

---

lib/presets/custom/angular/deliver/prebuild.js
package.json
yarn.lock

In the new version of Angular (which is initialized by default by the Azion CLI) it has SSR functionalities. As a result, the folder structure resulting from the build has a new subdivision: Browser and Server. We currently only support code on the Browser side (in deliver mode).
This PR moves the contents of the '.edge/storage/browser' folder to the root of the storage (.edge/storage/) and displays an alert if the user is using SSR resources.

fix: angular deliver preset

---

lib/build/bundlers/polyfills/node/globals/process.cjs
lib/build/bundlers/polyfills/polyfills-manager.js

It was identified that the node:process(esm) polyfill when used with webpack does not allow the process.env to be changed.
Webpack replaces all occurrences of process.env with an object that contains the environment variables defined at compile time. If your code is trying to modify process.env after Webpack has already made its replacements, this can cause problems.
Therefore, when you export as CommonJS, you can override process.env because modules are processed at request time. However, when you export as ESM, you cannot override process.env because the modules are processed before any code is executed.
```js
This is what is causing the error TypeError: Cannot set property env of #<Object> which has only one getter.
```

fix: node process polyfill to commonjs

---

lib/build/dispatcher/dispatcher.js

It was identified that when using the fs polyfill, global code injection into the worker was executed in the entry.
Therefore, it is necessary to separate what is injected into the entry and what is injected into the worker banner.
Error: 
```js
MEM_FILES = globalThis.vulcan.__FILES__;
TypeError: Cannot read properties of undefined (reading '__FILES__')
at vulcan-node-modules-polyfills:fs
```

fix: order code injection build

---

lib/presets/custom/next/compute/default/prebuild/index.js

When the next.js project is hybrid, an error was identified in the global variable _ENTRIES.
So it is necessary to inject this var at the top of the worker (onBanner).
Erro: 
```js
RUNTIME ERROR   ReferenceError: _ENTRIES is not defined
```

fix: added to globalVar _ENTRIES for banner injection

---

examples/simple-js-env-vars/README.md
examples/simple-js-env-vars/main.js
examples/simple-js-env-vars/package.json
examples/simple-js-env-vars/vulcan.config.js
lib/build/bundlers/esbuild/plugins/azion-polyfills/azion-polyfills.plugins.js
lib/build/bundlers/polyfills/polyfills-manager.js
lib/build/bundlers/webpack/plugins/azion-polyfills/azion-polyfills.plugins.js
lib/build/dispatcher/helpers/helpers.js
lib/env/polyfills/azion/env-vars/context/env-vars.context.js
lib/env/polyfills/azion/env-vars/context/env-vars.context.test.js
lib/env/polyfills/azion/env-vars/context/index.js
lib/env/polyfills/azion/env-vars/env-vars.polyfills.js
lib/env/polyfills/azion/env-vars/env-vars.polyfills.test.js
lib/env/polyfills/azion/env-vars/index.js
lib/env/polyfills/index.js
lib/env/runtime.env.js
package.json
tests/e2e/simple-js-env-vars.test.js
yarn.lock

Adding support [Azion environment-variables](https://www.azion.com/en/documentation/products/edge-functions/environment-variables/)  in local environment.
```js
const apiToken = Azion.env.get('API_SERVICE_TOKEN');
```
- We are adding support for the env-vars api for the local environment.
- This `polyfill` loads the .env  variables.
- Inserted the usage example in `/examples/simple-js-env-vars`.
Use:
To test usage, check `/examples/simple-js-env-vars/README.md`

feat: support env vars in local environment

---

examples/simple-js-firewall-event/README.md
examples/simple-js-firewall-event/main.js
examples/simple-js-firewall-event/package.json
examples/simple-js-firewall-event/vulcan.config.js
lib/build/dispatcher/dispatcher.js
lib/commands/build.commands.js
lib/commands/dev.commands.js
lib/constants/messages/build.messages.js
lib/env/polyfills/azion/firewall-event/context/firewall-event.context.js
lib/env/polyfills/azion/firewall-event/context/firewall-event.context.test.js
lib/env/polyfills/azion/firewall-event/context/index.js
lib/env/polyfills/azion/firewall-event/index.js
lib/env/runtime.env.js
lib/env/server.env.js
lib/main.js
lib/providers/azion/firewall_worker.js
lib/utils/helperHandlerCode/helperHandlerCode.js
lib/utils/helperHandlerCode/helperHandlerCode.test.js
lib/utils/helperHandlerCode/index.js
lib/utils/index.js
tests/e2e/simple-js-firewall-event.test.js
tests/utils/project-initializer.js

This feature aims to provide support for the firewall event API in the local environment and support when building firewall workers.
`For more details and how to run check out:
/examples/simple-js-firewall-event/README.md`
Example:
```js
addEventListener("firewall", (event) => {
// https://www.azion.com/en/documentation/products/edge-application/edge-functions/runtime/api-reference/metadata/
// In local development, the metadata is mocked.
const { geoip_country_name } = event.request.metadata;
event.addRequestHeader("X-Broccoli-Cooking-Method", "Boiling");
event.addResponseHeader("X-Broccoli-Cooking-Method", "Barbecue");
// event respondWith or event.deny must be called
event.respondWith(
new Response("The broccoli is burning.", {
headers: {
"X-Fire-Status": "On",
"X-Fire-Type": "Coal", …
```

feat(experimental): firewall event api support

---

examples/simple-js-firewall-event/README.md
examples/simple-js-firewall-event/main.js
examples/simple-js-firewall-event/package.json
examples/simple-js-firewall-event/vulcan.config.js
lib/build/dispatcher/dispatcher.js
lib/commands/build.commands.js
lib/commands/dev.commands.js
lib/constants/messages/build.messages.js
lib/env/polyfills/azion/firewall-event/context/firewall-event.context.js
lib/env/polyfills/azion/firewall-event/context/firewall-event.context.test.js
lib/env/polyfills/azion/firewall-event/context/index.js
lib/env/polyfills/azion/firewall-event/index.js
lib/env/runtime.env.js
lib/env/server.env.js
lib/main.js
lib/providers/azion/firewall_worker.js
lib/utils/helperHandlerCode/helperHandlerCode.js
lib/utils/helperHandlerCode/helperHandlerCode.test.js
lib/utils/helperHandlerCode/index.js
lib/utils/index.js
tests/e2e/simple-js-firewall-event.test.js
tests/utils/project-initializer.js

This feature aims to provide support for the firewall event API in the local environment and support when building firewall workers.
`For more details and how to run check out:
/examples/simple-js-firewall-event/README.md`
Example:
```js
addEventListener("firewall", (event) => {
// https://www.azion.com/en/documentation/products/edge-application/edge-functions/runtime/api-reference/metadata/
// In local development, the metadata is mocked.
const { geoip_country_name } = event.request.metadata;
event.addRequestHeader("X-Broccoli-Cooking-Method", "Boiling");
event.addResponseHeader("X-Broccoli-Cooking-Method", "Barbecue");
// event respondWith or event.deny must be called
event.respondWith(
new Response("The broccoli is burning.", {
headers: {
"X-Fire-Status": "On",
"X-Fire-Type": "Coal", …
```

feat: firewall event api support - Experimental

---

examples/simple-js-network-list-with-firewall/README.md
examples/simple-js-network-list-with-firewall/azion.config.js
examples/simple-js-network-list-with-firewall/main.js
examples/simple-js-network-list-with-firewall/package.json
examples/simple-js-network-list-with-firewall/vulcan.config.js
examples/simple-js-network-list/README.md
examples/simple-js-network-list/azion.config.js
examples/simple-js-network-list/main.js
examples/simple-js-network-list/package.json
examples/simple-js-network-list/vulcan.config.js
lib/build/bundlers/polyfills/polyfills-manager.js
lib/env/polyfills/azion/network-list/context/index.js
lib/env/polyfills/azion/network-list/context/network-list.context.js
lib/env/polyfills/azion/network-list/context/network-list.context.test.js
lib/env/polyfills/azion/network-list/index.js
lib/env/polyfills/azion/network-list/network-list.polyfills.js
lib/env/polyfills/index.js
lib/env/runtime.env.js
package.json
tests/e2e/simple-js-network-list-with-firewall.test.js
tests/e2e/simple-js-network-list.test.js
yarn.lock

This feature supports Azion Network List in the local dev environment, which reads the file azion.config.js which must contain networks.
- /examples/simple-js-network-list
- /examples/simple-js-network-list-with-firewall
_Important: For more usage details, please visit the examples README._
```js
export default async function main(event) {
const request = event.request;
if (
!request.headers.get("x-network-list-id") ||
!request.headers.get("x-element")
) {
return new Response("Missing headers", { status: 400 });
}
let network_list_id = request.headers.get("x-network-list-id");
let element = request.headers.get("x-element");
let response_headers = new Headers();
response_headers.set("X-Element", element);
if (Azion.networkList.contains(network_list_id, element)) { …
```

feat: add support to network list api

---

lib/commands/build.commands.js
lib/main.js

In the build command, when the --useNodePolyfills true | false, --useOwnWorker true| false was prioritized over other configuration options (vulcan.config.js, .vulcan and preset config).
This is available in any preset for testing we will use /examples/simple-js-esm.
```bash
vulcan build --preset javascript --mode compute
```
With the command above, the .vulcan will be generated, and it will contain useNodePolyfills false. To change via command option, execute below:
```bash
vulcan build --preset javascript --mode compute --useNodePolyfills true
```

fix: priority in build command options

---

lib/build/bundlers/webpack/webpack.config.js
lib/presets/custom/rustwasm/compute/prebuild.js
package.json
yarn.lock

When tsconfg.json does not exist in the typescript project ts-loader rule is ignored.
This occurred in the rust preset that uses webpack and contains files .ts in your build.
Changing the manifest generation from target to path.

fix: webpack config when ts loader

---

lib/presets/custom/next/compute/default/handler/images.js
lib/presets/custom/next/compute/handler.js

In this PR:
Create initial structure to handle image processing in Nextjs preset (compute mode).
At this moment return the image without image processing.

feat: handle _next/image paths in Nextjs preset

---

lib/presets/custom/next/compute/default/handler/routing/index.js
lib/presets/custom/next/compute/default/handler/routing/pcre.js
lib/presets/custom/next/compute/default/handler/routing/routes-matcher.js
lib/presets/custom/next/compute/default/prebuild/index.js
lib/presets/custom/next/compute/default/prebuild/mapping/process-mapping.js
lib/presets/custom/next/compute/default/prebuild/validation/support.js
lib/presets/custom/next/compute/handler.js
lib/presets/custom/next/compute/utils/next.js

This PR fixes a NextJs application that uses dynamic routes and i18n at the same time.
Using both types of routes at the same time was causing route conflicts and always returning the content of the dynamic route.

fix: i18n and dynamic routes

---

lib/presets/custom/angular/deliver/prebuild.js
lib/presets/custom/astro/deliver/prebuild.js
lib/presets/custom/eleventy/deliver/prebuild.js
lib/presets/custom/emscripten/compute/prebuild.js
lib/presets/custom/gatsby/deliver/prebuild.js
lib/presets/custom/hexo/deliver/prebuild.js
lib/presets/custom/hugo/deliver/prebuild.js
lib/presets/custom/next/compute/prebuild.js
lib/presets/custom/next/deliver/prebuild.js
lib/presets/custom/react/deliver/prebuild.js
lib/presets/custom/rustwasm/compute/prebuild.js
lib/presets/custom/vue/deliver/prebuild.js
lib/presets/default/html/deliver/prebuild.js
lib/presets/default/javascript/compute/prebuild.js
lib/presets/default/typescript/compute/prebuild.js
lib/utils/generateManifest/fixtures/schema.js
lib/utils/generateManifest/generateManifest.utils.js

In this PR:
- Set default name to presets rules;
- Make name required in azion config rules;
- Change behavior attribute 'rule' to 'name' in generated manifest (requested by Azion CLI);

chore: adjusts manifest rules names

---

.prettierignore
lib/presets/custom/angular/deliver/prebuild.js
lib/presets/custom/astro/deliver/prebuild.js
lib/presets/custom/eleventy/deliver/prebuild.js
lib/presets/custom/gatsby/deliver/prebuild.js
lib/presets/custom/hexo/deliver/prebuild.js
lib/presets/custom/hugo/deliver/prebuild.js
lib/presets/custom/next/compute/prebuild.js
lib/presets/custom/next/deliver/prebuild.js
lib/presets/custom/react/deliver/prebuild.js
lib/presets/custom/vue/deliver/prebuild.js
lib/presets/default/html/deliver/prebuild.js
lib/utils/generateManifest/fixtures/azion.config.js
lib/utils/generateManifest/fixtures/schema.js
lib/utils/generateManifest/generateManifest.utils.js
lib/utils/generateManifest/generateManifest.utils.test.js

Adding the origin configuration to the manifest.
Example:
`azion.config.js`
```js
export default {
origin: [
{
name: "my origin storage",
type: "object_storage",
bucket: "mybucket",
prefix: "myfolder",
},
],
rules: {
request: [
{
match: "/^/_statics/;", // start with /_statics
setOrigin: {
name: "my origin storage",
type: "object_storage",
},
}
],
},
};
```
The manifest generated in: `./.edge/manifest.json`
```json
{
"origin": [
{
"name": "my origin storage",
"origin_type": "object_storage",
"bucket": "mybucket",
"prefix": "myfolder"
}
],
"cache": [],
"rules": [
...
{
"criteria": [
[
{
"variable": "${uri}",
"operator": "matches",
"conditional": "if",
"input_value": "/^/_statics/;"
}
]
],
"behaviors": [
{
"name": "set_origin",
"target": "my origin storage"
}
]
}
]
}
```

feat: adding the origin configuration to the manifest

---

lib/build/dispatcher/dispatcher.js
lib/utils/generateManifest/generateManifest.utils.js
lib/utils/generateManifest/generateManifest.utils.test.js

When generating the manifest, a temporary file is now created due to generation steps. 
`Loadash` was also used to merge the configurations.

fix: generating a temporary file for creating the manifest

---

lib/build/bundlers/polyfills/node/globals/process.cjs

Change for process env support in Runtime.
Now the process env is checked before initialization and if it exists it is loaded, if not it is defined with a new object.

fix: process env support at runtime

---

lib/env/server.env.js

This solves #330 
1. Set ignoreInitial to true to prevent double execution of watcher actions. This avoids triggering actions when the first build changes files that are being watched but should not trigger any action.
2. Introduced an ignored list to prevent watcher actions when IDEs change non-source files.
3. Defined only the essential filesystem actions to monitor. 
4. Added feedback indicating that a watcher is in place.
Please review the changes. Let me know if further modifications are needed.

chore: improve watcher

---

tests/e2e/docusaurus-static.test.js

- Fixes lint errors in docusaurus-static.test.js according to the rules defined in .eslintrc.json.

ci: fixes lint errors

---

lib/utils/generateManifest/generateManifest.utils.js
lib/utils/generateManifest/generateManifest.utils.test.js
lib/utils/generateManifest/helpers/azion.config.example.js
lib/utils/generateManifest/helpers/schema.js
lib/utils/generateManifest/strategy/implementations/cacheManifestStrategy.js
lib/utils/generateManifest/strategy/implementations/domainManifestStrategy.js
lib/utils/generateManifest/strategy/implementations/originManifestStrategy.js
lib/utils/generateManifest/strategy/implementations/rulesManifestStrategy.js
lib/utils/generateManifest/strategy/manifestContext.js
lib/utils/generateManifest/strategy/manifestStrategy.js

Adding support for domains in the manifest generation, including the Azion API parameters for creating one or more domains.
The output was added to the `.edge/manifest.json` file that will be consumed by the CLI.
**Example:**
The full example in `./lib/utils/generateManifest/helpers/azion.config.example.js`
```js
module.exports = {
domain:  {
name: 'my_domain',
cnameAccessOnly: false, // Optional, defaults to false
cnames: ['www.example.com'], // Optional
edgeApplicationId: 12345, // Optional
edgeFirewallId: 12345, // Optional
digitalCertificateId: 'lets_encrypt', // 'lets_encrypt' or null
mtls: {
verification: 'enforce', // 'enforce' or 'permissive'
trustedCaCertificateId: 12345,
crlList: [111, 222],
}, // Optional
},
};
```
**Tests:**
```bash
yarn jest …
```

feat: adding support for domains in manifest generation.

---

lib/utils/generateManifest/generateManifest.utils.test.js
lib/utils/generateManifest/helpers/azion.config.example.js
lib/utils/generateManifest/helpers/schema.js
lib/utils/generateManifest/strategy/implementations/originManifestStrategy.js

Added parameters for origins in manifest generation based on API v3.
Example:
```js
module.exports = {
origin: [
{
name: 'myneworigin', // Required
type: 'object_storage', // Required. single_origin, load_balancer, object_storage, live_ingest.
bucket: 'blue-courage', // Required for object_storage
prefix: '0101010101001', // Optional. Default '' if not provided
},
]
}
```
For the full example, see: `./lib/utils/generateManifest/helpers/azion.config.example.js`
```bash
yarn jest lib/utils/generateManifest/generateManifest.utils.test.js
```

feat: added all origins parameters to the manifest

---

lib/utils/generateManifest/generateManifest.utils.js
lib/utils/generateManifest/generateManifest.utils.test.js
lib/utils/generateManifest/helpers/azion.config.example.js
lib/utils/generateManifest/helpers/schema.js
lib/utils/generateManifest/strategy/implementations/domainManifestStrategy.js
lib/utils/generateManifest/strategy/implementations/purgeManifestStrategy.js

Added parameters for purge in manifest generation based on API v3.
Example:
```js
module.exports = {
purge: [
{
type: 'url',
urls: ['http://www.example.com/image.jpg'],
},
{
type: 'cachekey',
urls: ['http://www.example.com/image1.png', 'http://www.example.com/image2.png'],
method: 'delete',
},
{
type: 'wildcard',
urls: ['http://www.example.com/*'],
},
],
}
```
For the full example, see: `./lib/utils/generateManifest/helpers/azion.config.example.js`
```bash
yarn jest lib/utils/generateManifest/generateManifest.utils.test.js -t "jsToJson - Purge"
```
fix: update digitalCertificateId field configuration to accept number type
It was updated in the Ajv schema to authorize multiple types.
And added the number type in the digitalCertificateId field of the Domain.

feat: added purge parameters to the manifest

---

lib/build/dispatcher/dispatcher.js
lib/constants/messages/build.messages.js

This PR refactors the code in the Dispatcher class to merge the user's`azion.config.js` file with the preset `azion.config.js` file. It uses the `lodash.mergeWith` function to combine the two configurations, giving priority to the user's config. This ensures that the final `configModule` used in the code is a merged version of the two configurations.
Fix: Typo in pre-build success message

fix: merge azion.config user with preset azion.config

---

lib/env/polyfills/azion/fetch-event/context/fetch-event.context.js
lib/main.js

FetchEventContext class to handle event initialization and args loading
The args file path was set in `globalThis.vulcan.argsPath`

feat: add FetchEventContext class to handle event initialization and args loading

---

lib/build/dispatcher/dispatcher.js
lib/constants/messages/build.messages.js

- Entering invalid preset name in error message.
- Changing the command to list presets in the error message from `azion presets ls` to `npx edge-functions presets ls`.

fix: update error message for invalid build preset

---

lib/env/vulcan.env.js

We are removing the import of the azion package when creating the azion.config for use with defineConfig.
This is to make the installation of the package no longer mandatory.

fix: removing the import of the azion package when creating the azion.config

---

lib/presets/nuxt/azion.config.js
lib/presets/nuxt/config.js
lib/presets/nuxt/handler.js
lib/presets/nuxt/prebuild.js
lib/utils/presets/presets.utils.test.js
tests/e2e/nuxt-static.test.js

Added new preset to handle Nuxt static projects.
This PR relates to:
- https://github.com/aziontech/vulcan-examples/pull/62
- https://github.com/aziontech/azion-samples/pull/155

feat(presets): new preset nuxt

---

lib/commands/build.commands.js
lib/main.js
lib/utils/checkingProjectType/checkingProjectType.test.js
lib/utils/checkingProjectType/checkingProjectType.utils.js
lib/utils/checkingProjectType/index.js
lib/utils/index.js

When the preset is JavaScript or Typescript, it is not necessary to pass the --preset flag in the build command.
It is still allowed to pass --preset javascript or typescript!

fix: removing the need to pass the preset flag when js

---

lib/commands/build.commands.js

Fixing entry file extension order when presetting javascript or typescript

fix: incorrect file extension in build command

---

.github/workflows/test-nodejs-apis.yml
.gitmodules
Dockerfile
README.md
docker-compose.yml
docs/nodejs-apis.md
package.json
tasks/process-reports-nodejs-apis.js
tests/nodejs-apis/async-hooks.test.js
tests/nodejs-apis/buffer.test.js
tests/nodejs-apis/crypto.test.js
tests/nodejs-apis/events.test.js
tests/nodejs-apis/fs.test.js
tests/nodejs-apis/http.test.js
tests/nodejs-apis/module.test.js
tests/nodejs-apis/os.test.js
tests/nodejs-apis/path.test.js
tests/nodejs-apis/process.test.js
tests/nodejs-apis/stream.test.js
tests/nodejs-apis/string-decoder.test.js
tests/nodejs-apis/timers.test.js
tests/nodejs-apis/url.test.js
tests/nodejs-apis/util.test.js
tests/nodejs-apis/vm.test.js
tests/nodejs-apis/zlib.test.js
tests/scripts/setup-e2e-env.sh
tests/scripts/start-e2e-env.sh
tests/utils/project-initializer.js
tests/utils/project-stop.js

- async-hooks
- buffer
- crypto
- events
- fs
- http
- module
- os
- path
- process
- stream
- string-decoder
- timers
- url
- util
- vm
- zlib
- renaming from vulcan to bundler
- update subproject commit reference

test: add tests for Node.js APIs

---

lib/build/dispatcher/dispatcher.js
lib/env/vulcan.env.js
lib/presets/stencil/azion.config.js
package.json
yarn.lock

**Description:**
This pull request addresses an issue with module imports in the lib/env/vulcan.env.js file. The previous implementation attempted to use require() for ES Modules, which is not supported and caused errors.
**Changes Made:**
- Dynamic Import Handling:
- Implemented import() for loading ES Modules.
- Added a fallback to require() for CommonJS modules when import() fails with ERR_REQUIRE_ESM.
- Add `mathjs` temporarily until the new version of the `azion/config` package is released.

fix: import azion.config.js (presets)

---

Dockerfile
package.json
tests/e2e/angular-static.test.js
tests/e2e/astro-static.test.js
tests/e2e/docusaurus-static.test.js
tests/e2e/eleventy-static.test.js
tests/e2e/gatsby-static.test.js
tests/e2e/hexo-static.test.js
tests/e2e/jekyll-static.test.js
tests/e2e/next-12-3-4-config.test.js
tests/e2e/next-12-3-4-i18n.test.js
tests/e2e/next-12-3-4-middleware.test.js
tests/e2e/next-12-static.test.js
tests/e2e/next-13-5-6-config.test.js
tests/e2e/next-13-5-6-i18n.test.js
tests/e2e/next-13-5-6-middleware.test.js
tests/e2e/next-14-2-15-middleware.test.js
tests/e2e/next-node-pages-12-3-1-fs.test.js
tests/e2e/next-node-pages-12-3-1.test.js
tests/e2e/next-static.test.js
tests/e2e/nuxt-static.test.js
tests/e2e/react-static.test.js
tests/e2e/stencil-static.test.js
tests/e2e/svelte-static.test.js
tests/e2e/vitepress-static.test.js
tests/e2e/vue-vite-static.test.js
tests/e2e/vuepress-static.test.js
yarn.lock

This pull request includes updates to the end-to-end (E2E) test configurations for various static site projects. The changes primarily involve modifying the Puppeteer launch settings to enhance security by adding sandboxing arguments.
Changes to E2E test configurations:
Updated Puppeteer launch settings to include `--no-sandbox` and `--disable-setuid-sandbox` arguments.
The same changes were applied to other E2E test files for various static site projects, ensuring consistent security improvements across all tests.
fix: update azion library version to 1.12.1

test: add no-sandbox args for puppeteer launch in E2E tests

---

lib/presets/qwik/azion.config.js
lib/presets/qwik/config.js
lib/presets/qwik/handler.js
lib/presets/qwik/prebuild.js
lib/utils/presets/presets.utils.test.js
tests/e2e/qwik-static.test.js
tests/utils/project-initializer.js

Adding a new preset for static apps based in the Qwik framework.
Also adding the flag `--ignore-engines` for the yarn during the tests as some of the Qwik dependencies expects node 20, while we use node 18... It doesn't affect the build though.

feat: new preset qwik

---

package.json
yarn.lock

This pull request includes a small change to the `package.json` file. The change updates the version of the `azion` package from `^1.14.0-stage.4` to `^1.14.0`.

chore: update azion package version to 1.14.0

---

package.json
yarn.lock

This pull request includes a minor change to the `package.json` file. The change updates the version specification for the `azion` package from a caret (`^`) to a tilde (`~`), ensuring that only patch updates are allowed.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L58-R58): Changed the version specifier for `azion` from `^1.14.0` to `~1.14.0` to restrict updates to patch versions only.

chore: update azion package version to ~1.14.1

---

lib/commands/build/command.ts
lib/commands/build/modules/environment/environment.ts
lib/env/bundler.ts

This pull request includes several changes to the build command and environment setup processes in the project. The most important changes are focused on extending build configurations, simplifying the environment setup, and ensuring user configurations are always written.
* [`lib/commands/build/command.ts`](diffhunk://#diff-444d642d78d59bba66af2fc952fce0cfda79aa637e47c760756973acc864eb51R77): Added support for extending build configurations with a new `extend` property in the `build` object.
* [`lib/commands/build/modules/environment/environment.ts`](diffhunk://#diff-93f36286cb82f7746ff9eb116786e43075ae9147a80d5654ebb27cdfdd45b877L59-R59): Simplified the environment setup by removing the check for existing user configuration and always writing the merged configuration.
* …

fix: enhance build command with user-configurable extend option and streamline user config writing

---

package.json
yarn.lock

This pull request includes a minor dependency update in the `package.json` file. The version of the `azion` package has been updated from `1.20.0-stage.6` to `~1.20.0-stage.7` to ensure compatibility with the latest stable features.

fix: update azion dependency to version ~1.20.0-stage.7

---

lib/commands/build/build.ts
lib/commands/build/types.ts
lib/commands/config/command.ts
lib/commands/config/config.ts
lib/commands/config/types.ts
lib/env/server.ts
lib/main.ts
package.json
yarn.lock

This pull request introduces two main improvements: a new placeholder replacement feature for configuration management, and enhancements to the build and CLI experience. The placeholder replacement allows users to easily substitute values throughout their `azion.config`, while the build command now supports generating only the configuration file. Several usability and error-handling improvements have also been made.
**Configuration management enhancements:**
* Added a new `replace` command to the `config` CLI, enabling recursive replacement of all occurrences of a placeholder string with a new value in the `azion.config` file. This includes the new `replaceConfig` function and supporting logic. [[1]](diffhunk://#diff-70648c03d531421eb6b0a58d87aa9facbf44d478c0fc016cce8689e498c68060R5-R54) …

feat: improvements, command replace and flag only-generate-config to build command

---

lib/commands/build/build.ts
lib/commands/build/command.ts
lib/commands/build/modules/storage/storage.ts
lib/commands/build/types.ts
package.json
yarn.lock

This pull request introduces improvements to the build command, including enhanced error messaging, new build options, and a dependency update. The main changes focus on providing better user feedback, expanding build configuration capabilities, and ensuring compatibility with the latest dependencies.
**Build Command Enhancements:**
* Added a warning message when the `skipFrameworkBuild` option is enabled to provide clearer feedback during the build process (`lib/commands/build/build.ts`).
* Introduced the `onlyGenerateConfig` option to the `BuildCommandOptions` interface and passed it through the build command, allowing users to generate only the configuration file without a full build (`lib/commands/build/types.ts`, `lib/commands/build/command.ts`). …

fix: add onlyGenerateConfig option and improve storage error message

---

lib/commands/build/build.ts
lib/commands/build/modules/bindings/bindings.ts
lib/commands/build/modules/storage/storage.ts
lib/constants.ts
lib/env/runtime.ts
lib/env/server.ts
package.json
yarn.lock

This pull request primarily refactors and simplifies the handling of storage bindings and metadata in the build process, removing legacy placeholder logic and improving how storage name and prefix are injected and used throughout the codebase. It also updates the Azion SDK dependency and streamlines the creation of storage symlinks and metadata files.
**Storage Bindings and Metadata Refactor:**
- Removed usage of `MANIFEST_PLACEHOLDERS` for storage bucket names and replaced it with direct usage of actual storage names throughout the binding and metadata logic, simplifying the code and reducing indirection. [[1]](diffhunk://#diff-61d2c271c50f41e269efa59423ebf921e448cb1324976db85232cdd0989431c8L5-R5) [[2]](diffhunk://#diff-561ab956a0b904914573a9544f92493c5493b6e14d30372365bcdd9c5c7f6e59L16-L …

feat!: update all preset azion.config files for API v4 compatibility

---

lib/commands/build/modules/bindings/bindings.ts
lib/commands/build/modules/storage/storage.ts
lib/env/server.ts
package.json
yarn.lock

This pull request focuses on improving storage handling and environment setup for edge functions, particularly around bucket and prefix management. The main changes include better cleanup of storage directories and symlinks, refactoring how bucket and prefix values are set and accessed globally, and updating type signatures to support these improvements.
**Storage management improvements:**
- Enhanced the `createStorageSymlink` function to clean up all existing folders (except the current prefix) in the target directory, removing symbolic links, directories, or files as needed, and improved logging for these operations. Also, improved logic for removing existing symlinks or directories before creating a new symlink.
- Removed temporary global variable assignments for bucket name and …

fix: improve storage cleanup and move bucket globals to server initialization

---

package.json
yarn.lock

This pull request updates the `azion` dependency in `package.json` to use the stable `2.1.0` release instead of the previous stage version. This is a minor change that ensures the project uses the latest stable version of the package.

chore: update azion dependency from 2.1.0-stage.1 to 2.1.0

---

CHANGELOG.md
README.md
lib/commands/build/modules/bindings/bindings.ts
lib/commands/build/modules/storage/storage.ts
lib/commands/config/command.ts
lib/commands/config/config.test.ts
lib/commands/config/config.ts
lib/commands/presets/presets.test.ts
lib/env/server.ts
lib/main.ts
package.json
yarn.lock

⚠️ WARNING: Configuration changes required for azion.config files
This commit renames several properties to remove the "Edge" prefix:
- edgeFunctions → functions
- runtimeFunctionsEnabled → functionsEnabled
- EdgeConnector → Connector
- Edge Storage → Storage
- Edge Firewall → Firewall
- Edge Application → Application
By company decision, this is NOT a breaking change. However, users need to update their azion.config files to use the new property names. The old names are deprecated and will be removed in a future version.
Please update your configuration files accordingly.

Release 6.1.0
