- lib/env/runtime.env.js
https://github.com/aziontech/vulcan/assets/12740219/b24fb680-9689-4088-80b3-79b99c30a468
> [ISSUE-77] feat: enable 'eval' in the local env

- .eslintrc.json
- .gitignore
- aliases.js
- jsconfig.json
- lib/build/dispatcher/dispatcher.js
- lib/commands/auth.commands.js
- lib/commands/build.commands.js
- lib/commands/deploy.commands.js
- lib/commands/dev.commands.js
- lib/commands/index.js
- lib/commands/init.commands.js
- lib/commands/logs.commands.js
- lib/commands/presets.commands.js
- lib/commands/storage.commands.js
- lib/constants/framework-initializer.constants.js
- lib/constants/messages/build.messages.js
- lib/env/polyfills/fetch.polyfills.js
- lib/env/runtime.env.js
- lib/env/server.env.js
- lib/env/vulcan.env.js
- lib/main.js
- lib/platform/actions/core/auth.actions.js
- lib/platform/services/base.service.js
- lib/presets/custom/next/deliver/prebuild.js
- lib/utils/getUrlFromResource/getUrlFromResource.utils.js
- lib/utils/getUrlFromResource/index.js
- lib/utils/index.js
- package.json
- yarn.lock
- (refactor) moved commands from main.js to a #commands layer
-  (feat) local env with hot reload
- (feat) vulcan.env place to store build configurations
- (fix) vue/angular initializer (preset)
- (fix) use process.exit(1) in cases where the server fails
- (fix) local environment fetch
> feat: hot reload local env

- lib/env/runtime.env.js
- lib/presets/custom/next/compute/config.js
- lib/presets/custom/next/compute/node/index.js
- lib/presets/custom/next/compute/prebuild.js
This PR adds:
- Nextjs runtime validation fix;
- Nextjs version validation fix;
- Fix utils resolve in build;
- Fix local env `eval` enable;
> fix: Next build fix and improvements

- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/next-compute-js-server.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/response-cache/index.js
- lib/presets/custom/next/compute/node/index.js
- lib/presets/custom/next/compute/node/prebuild/statics/index.js
Changes:
- removed temp message on run node
- removing static folder before generating new build
- added temporary cache response
> fix: response cache and improvements

- .gitignore
- examples/simple-js-esm/main.js
- lib/commands/init.commands.js
- lib/constants/messages/global.messages.js
- lib/env/server.env.js
- lib/env/vulcan.env.js
- lib/utils/exec/exec.utils.js
In this release, we've enhanced the exec function in #utils for better management of 'exit' and 'close' events, while also introducing a streamlined .vulcan file that replaces the older .vulcan.env file, now being generated during both the build and init command processes to store preset information, thus simplifying the workflow by eliminating the need for redundant preset specifications in the [Azion-CLI](https://github.com/aziontech/azion-cli).
> Release 1.6.0

- lib/presets/custom/next/compute/node/custom-server/12.3.1/index.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/base-http/compute-js.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/common.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/compute-js.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/config.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/load-components.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/next-compute-js-server.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/next.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/require.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/response-cache/index.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/server/serve-static.js
- lib/presets/custom/next/compute/node/custom-server/12.3.1/util/etag.js
- lib/presets/custom/next/compute/node/index.js
- lib/presets/custom/next/compute/node/prebuild/statics/index.js
Changes:
- custom server code compiled for javascript
- load the next.config file
> fix: custom server code and config file

- lib/build/dispatcher/dispatcher.js
- lib/constants/messages/build.messages.js
- lib/utils/vercel/vercel.utils.js
Changes:
- check if dependencies are installed (node_modules)
- log build vercel cli (stdio: inherit)
> feat: check if dependencies are installed and log vercel cli

- lib/platform/actions/core/storage.actions.js
- lib/platform/services/storage.service.js
- removing readFile encoding from storage API
- adding the stage url to the storage API
> fix: removing utf8 when reading file

- lib/env/server.env.js
This PR propose to change the host from 'localhost' to '0.0.0.0' to be able access the development mode when Vulcan run inside a Docker.
> chore: change the host from 'localhost' to '0.0.0.0' on run server

- .github/workflows/release.yml
This job is used to merge main into stage whenever a deployment is made, ensuring that stage is synchronized with the latest version.
> ci: sync stage automation

- .commitlintrc.json
- .husky/commit-msg
- .husky/pre-commit
- package.json
- yarn.lock
Ensure all of our commit messages follow a standard convention. This checks messages commit-message hook.
We are using Husky which is a tool to run scripts at different stages of the git process.
For messages we use @commitlint/config-conventional with a set of rules.
Also during pre-commit, **eslint** and **prettier** are checked.
**Incorrect message**: 
**Success message**:
> ci: commit convention

- .github/workflows/azioncli.yml
- tests/azion_cli/link.exp
- tests/azion_cli/test.sh
- action azioncli
- test build flow with vulcan 
- notify the slack channel
> Test: azion cli

- .github/workflows/release.yml
- .releaserc
- CODEOWNERS
In this PR:
- Fix merge main into stage job;
- Add github token (with correct permissions) to jobs;
- Update CODEOWNERS file;
> ci: fix deploy workflow

- lib/presets/custom/next/compute/default/handler/routing/http.js
- lib/presets/custom/next/compute/default/handler/routing/http.test.js
- lib/presets/custom/next/compute/default/handler/routing/index.js
- lib/presets/custom/next/compute/default/handler/routing/matcher.js
- lib/presets/custom/next/compute/default/handler/routing/matcher.test.js
- lib/presets/custom/next/compute/default/handler/routing/pcre.js
- lib/presets/custom/next/compute/default/handler/routing/pcre.test.js
- lib/presets/custom/next/compute/default/handler/routing/routes-matcher.js
- lib/presets/custom/next/compute/default/handler/routing/utils.js
- lib/presets/custom/next/compute/default/handler/routing/utils.test.js
- lib/presets/custom/next/compute/default/prebuild/edge/index.js
- lib/presets/custom/next/compute/default/prebuild/index.js
- lib/presets/custom/next/compute/default/prebuild/mapping/assets.js
- lib/presets/custom/next/compute/default/prebuild/mapping/assets.test.js
- lib/presets/custom/next/compute/default/prebuild/mapping/index.js
- lib/presets/custom/next/compute/default/prebuild/mapping/index.test.js
- lib/presets/custom/next/compute/default/prebuild/mapping/process-mapping.js
- lib/presets/custom/next/compute/default/prebuild/mapping/process-mapping.test.js
- lib/presets/custom/next/compute/prebuild.js
- lib/presets/custom/next/compute/utils/fs.js
- lib/presets/custom/next/compute/utils/routing.js
- lib/utils/vercel/vercel.utils.js
Tests to Nextjs routing and edge runtime solution.
Based on [azion-framework-adapter](https://github.com/aziontech/azion-framework-adapter) code .
> Tests - Nextjs routing and edge runtime

- examples/simple-js-esm/main.js
- tests/e2e/gatsby-static.test.js
- tests/e2e/next-12-3-4-config.test.js
- tests/e2e/next-12-3-4-i18n.test.js
- tests/e2e/next-12-3-4-middleware.test.js
- tests/e2e/next-13-5-6-config.test.js
- tests/e2e/next-13-5-6-i18n.test.js
- tests/e2e/next-13-5-6-middleware.test.js
- tests/e2e/next-node-pages-12-3-1-fs.test.js
- tests/e2e/next-node-pages-12-3-1.test.js
- tests/e2e/next-static.test.js
- tests/utils/docker-env-actions.js
This "PR" adds tests for the NextsJS examples.
> test: e2e tests for frameworks examples

- README.md
- docs/nextjs.md
- docs/overview.md
- docs/presets.md
In this PR:
- Add nextjs doc;
- Update README and other docs;
> docs: update docs

- examples/next/next-12-static/lib/posts.js
- examples/next/next-12-static/pages/index.jsx
- examples/next/next-12-static/pages/post/[id].jsx
- examples/next/next-13-static/lib/posts.js
- examples/next/next-13-static/src/pages/index.jsx
- examples/next/next-13-static/src/pages/post/[id].jsx
- lib/presets/custom/next/deliver/prebuild.js
- lib/presets/custom/next/utils.next.js
In this PR:
- fix Nextjs config file read. Accepts mjs extension;
- Improve nextjs static examples. Mock external API data get (used in generate pages).
> fix: Nextjs config file read

- lib/utils/vercel/vercel.utils.js
- lib/utils/vercel/vercel.utils.test.js
This PR update the version of Vercel cli from 32.2.1 to 32.6.1.
> chore: update vercel cli from 32.2.1 to 32.6.1

- lib/presets/custom/next/compute/default/handler/routing/routes-matcher.js
- lib/presets/custom/next/compute/default/prebuild/index.js
This PR aims to fix the access to no default i18n locales routes.
> fix:  error on access of non-default locales routes in NextJs

- lib/presets/custom/angular/deliver/prebuild.js
- lib/presets/custom/astro/deliver/prebuild.js
- lib/presets/custom/eleventy/deliver/prebuild.js
- lib/presets/custom/hexo/deliver/prebuild.js
- lib/presets/custom/hugo/deliver/prebuild.js
- lib/presets/custom/next/deliver/prebuild.js
- lib/presets/custom/react/deliver/prebuild.js
- lib/presets/custom/svelte/deliver/prebuild.js
- lib/presets/custom/vue/deliver/prebuild.js
This Regex checks that the url does not end in " /" or some extension... that is, the "path"+ "index.html" must be added.
> fix: presets rules (rewrite)

- CHANGELOG.md
- lib/constants/framework-initializer.constants.js
- lib/presets/default/html/deliver/prebuild.js
- lib/utils/copyDirectory/copyDirectory.utils.js
- package.json
> Release 2.6.2: Some Fixes

- README.md
- lib/utils/generateManifest/generateManifest.utils.test.js
Updating links in README.
Correcting what was expected in a GenerateManifest test.
> chore: fixing docs and tests

- README.md
- lib/utils/generateManifest/generateManifest.utils.test.js
Updating example links in README.
Bonus:
Correcting what was expected in the Generate Manifest test.
> chore: updating links in README

- lib/presets/custom/react/deliver/prebuild.js
- lib/presets/custom/vue/deliver/prebuild.js
- React with Vue was not being supported.
- Vue with Vite + TS was not being supported.
> fix: react/vue with vite (preset)

- .prettierignore
- lib/build/bundlers/esbuild/plugins/azion-polyfills/azion-polyfills.plugins.test.js
- lib/build/bundlers/esbuild/plugins/node-polyfills/node-polyfills.plugins.test.js
- lib/build/bundlers/polyfills/node/fs.js
- lib/build/bundlers/polyfills/polyfills-manager.js
- lib/build/bundlers/polyfills/polyfills-manager.test.js
- lib/build/bundlers/webpack/plugins/azion-polyfills/azion-polyfills.plugins.test.js
- lib/build/bundlers/webpack/plugins/node-polyfills/node-polyfills.plugins.test.js
- lib/build/dispatcher/dispatcher.js
- lib/env/polyfills/fs/context/fs.context.js
- lib/env/polyfills/fs/context/index.js
- lib/env/polyfills/fs/fs.polyfills.js
- lib/env/polyfills/fs/index.js
- lib/env/polyfills/fs/promises.polyfills.js
- lib/env/polyfills/index.js
- lib/env/runtime.env.js
- package.json
Use polyfills for sync fs operations and use runtime for async fs operations (callbacks and promises).
Also add support for fs in local server (simulates azion runtime behavior).
> feat: use runtime in async fs

- lib/constants/framework-initializer.constants.js
- lib/presets/docusaurus/deliver/azion.config.js
- lib/presets/docusaurus/deliver/config.js
- lib/presets/docusaurus/deliver/handler.js
- lib/presets/docusaurus/deliver/prebuild.js
- lib/utils/presets/presets.utils.test.js
- tests/e2e/docusaurus-static.test.js
Adds Docusaurus as a new deliver preset option.
As we're working in changes related to the examples repository, you'll have to trust me that I didn't cheat in the testing:
This PR relates to: https://github.com/aziontech/azion-samples/pull/110
> feat: New preset Docusaurus

- README.md
- lib/presets/vitepress/deliver/azion.config.js
- lib/presets/vitepress/deliver/config.js
- lib/presets/vitepress/deliver/handler.js
- lib/presets/vitepress/deliver/prebuild.js
- lib/utils/presets/presets.utils.test.js
- tests/e2e/vitepress-static.test.js
Adding a new preset for VitePress-based applications.
This PR relates to:
- https://github.com/aziontech/vulcan-examples/pull/55
- https://github.com/aziontech/azion-samples/pull/112
> feat(presets): vitepress

- lib/env/polyfills/fs/context/fs.context.js
- lib/env/polyfills/fs/fs.polyfills.js
- lib/env/polyfills/fs/promises.polyfills.js
This PR enable writeFile, rename and realpath from Node FS.
> feat: enable writeFile, rename and realpath from Node FS

- lib/build/dispatcher/dispatcher.js
- lib/env/vulcan.env.js
simplify merging of azion.config.js
update createAzionConfigFile to use defineConfig
> fix: checking if the project's azion.config exists

- .github/workflows/tests-e2e.yml
- tests/e2e/gatsby-static.test.js
- tests/e2e/simple-js-env-vars.test.js
- tests/e2e/simple-js-esm-node.test.js
- tests/e2e/simple-js-esm-worker.test.js
- tests/e2e/simple-js-esm.test.js
- tests/e2e/simple-js-firewall-event.test.js
- tests/e2e/simple-js-network-list-with-firewall.test.js
- tests/e2e/simple-js-network-list.test.js
- installing docker compose for e2e test
- fixing e2e tests to run dependency installation
> test(e2e): report e2e and fixing e2e tests to run dependency installation

- lib/presets/vuepress/azion.config.js
- lib/presets/vuepress/config.js
- lib/presets/vuepress/handler.js
- lib/presets/vuepress/prebuild.js
- lib/utils/presets/presets.utils.test.js
- tests/e2e/vuepress-static.test.js
Add preset for projects based in the VuePress framework.
This PR relates to:
- https://github.com/aziontech/bundler-examples/pull/65
- https://github.com/aziontech/azion-samples/pull/170
> feat(presets): new preset vuepress

- lib/presets/stencil/azion.config.js
- lib/presets/stencil/config.js
- lib/presets/stencil/handler.js
- lib/presets/stencil/prebuild.js
- lib/utils/presets/presets.utils.test.js
- tests/e2e/stencil-static.test.js
Add preset for projects based in the Stencil framework.
Relates to: https://github.com/aziontech/bundler-examples/pull/66
> feat(presets): new preset stencil

- lib/build/bundlers/webpack/plugins/babel-custom/babel-custom-loader.plugins.js
- lib/build/bundlers/webpack/plugins/babel-custom/index.js
- lib/build/bundlers/webpack/webpack.bundlers.js
- lib/build/dispatcher/dispatcher.js
- lib/env/vulcan.env.js
- lib/presets/stencil/azion.config.js
- package.json
- yarn.lock
This pull request introduces a custom Babel loader plugin to the Webpack configuration, updates the Webpack bundler to include this plugin, and adds necessary dependencies to the `package.json` file.
* [`lib/build/bundlers/webpack/plugins/babel-custom/babel-custom-loader.plugins.js`](diffhunk://#diff-59f8cb763a0a129d017bd9042624d5d6efc707586602e4dadb3caf7d1a0d199bR1-R40): Added a new `BabelCustomLoaderPlugin` class that configures Babel to use the `@babel/plugin-proposal-optional-chaining-assign` plugin for files matching the `.func.m?js` pattern.
* [`lib/build/bundlers/webpack/plugins/babel-custom/index.js`](diffhunk://#diff-e0135acee6dd4abbec5aeb8d533b2b9586b74157308add80853249aab0339dddR1-R3): Exported the `BabelCustomLoaderPlugin` from the new plugin file.
* …
> feat: add Babel custom loader plugin and update webpack configuration

- CHANGELOG.md
- Dockerfile
- package.json
- tests/e2e/angular-static.test.js
- tests/e2e/astro-static.test.js
- tests/e2e/docusaurus-static.test.js
- tests/e2e/eleventy-static.test.js
- tests/e2e/gatsby-static.test.js
- tests/e2e/hexo-static.test.js
- tests/e2e/jekyll-static.test.js
- tests/e2e/next-12-3-4-config.test.js
- tests/e2e/next-12-3-4-i18n.test.js
- tests/e2e/next-12-3-4-middleware.test.js
- tests/e2e/next-12-static.test.js
- tests/e2e/next-13-5-6-config.test.js
- tests/e2e/next-13-5-6-i18n.test.js
- tests/e2e/next-13-5-6-middleware.test.js
- tests/e2e/next-14-2-15-middleware.test.js
- tests/e2e/next-node-pages-12-3-1-fs.test.js
- tests/e2e/next-node-pages-12-3-1.test.js
- tests/e2e/next-static.test.js
- tests/e2e/nuxt-static.test.js
- tests/e2e/react-static.test.js
- tests/e2e/stencil-static.test.js
- tests/e2e/svelte-static.test.js
- tests/e2e/vitepress-static.test.js
- tests/e2e/vue-vite-static.test.js
- tests/e2e/vuepress-static.test.js
- yarn.lock
This pull request includes several updates and bug fixes, primarily focusing on upgrading dependencies, adding new arguments to Puppeteer launches in E2E tests, and updating the project version. The most important changes are summarized below:
* Upgraded the `azion` library dependency in `package.json` from `^1.12.0` to `^1.12.1`.
* Updated the base image in `Dockerfile` from `node:18-alpine3.17` to `node:18.20.5-alpine3.21`.
* Added `--no-sandbox` and `--disable-setuid-sandbox` arguments for Puppeteer launches in various E2E test files to improve test stability.
> Release 4.4.1

- package.json
- yarn.lock
Updating the azion package which contains corrections to the manifest transform command.
> fix: update azion package version to ~1.14.2

- README.md
- lib/commands/build/modules/prebuild/utils.ts
- lib/env/runtime.ts
- package.json
- tests/nodejs-apis/async-hooks.test.js
- tests/nodejs-apis/buffer.test.js
- tests/nodejs-apis/crypto.test.js
- tests/nodejs-apis/events.test.js
- tests/nodejs-apis/fs.test.js
- tests/nodejs-apis/http.test.js
- tests/nodejs-apis/module.test.js
- tests/nodejs-apis/os.test.js
- tests/nodejs-apis/path.test.js
- tests/nodejs-apis/process.test.js
- tests/nodejs-apis/stream.test.js
- tests/nodejs-apis/string-decoder.test.js
- tests/nodejs-apis/timers.test.js
- tests/nodejs-apis/url.test.js
- tests/nodejs-apis/util.test.js
- tests/nodejs-apis/vm.test.js
- tests/nodejs-apis/zlib.test.js
- yarn.lock
This pull request introduces several updates, including a deprecation notice for the webpack bundler, improvements to the `injectWorkerMemoryFiles` function, new runtime contexts, dependency updates, and adjustments to test configurations and expectations. Below is a categorized summary of the most important changes:
* Added a deprecation notice in the `README.md` to inform users that webpack bundler support will be discontinued in future releases, encouraging migration to esbuild for better performance and compatibility.
* Refactored the `injectWorkerMemoryFiles` function in `utils.ts` to use a recursive helper function (`processDirectory`) for better readability and maintainability. [[1]](diffhunk://#diff-101a730066700be1985da876619233dce4d09ee1fc92617d83797c641974dc8aL28-R38) …
> feat: updating azion lib with unenv 2.x and also env dev polyfills

- .github/workflows/test-e2e.yml
- Dockerfile
- lib/commands/build/modules/worker/constants.ts
- lib/commands/build/modules/worker/utils.ts
- lib/commands/build/modules/worker/worker.ts
- lib/env/edge-vm/edge-vm.ts
- lib/env/edge-vm/index.ts
- lib/env/edge-vm/types.ts
- lib/env/edge-vm/vm.ts
- lib/env/runtime.ts
- package.json
- yarn.lock
This pull request introduces a new `EdgeVM` implementation, replacing the previous `EdgeRuntime` dependency and providing a more customizable and extensible virtual machine for edge runtime simulation. It also includes type definitions and interfaces to support the new implementation, as well as updates to the project dependencies.
* Added `EdgeVM` and `VM` classes in `lib/env/edge-vm/vm.ts`, implementing a realm-like interface for code evaluation and dynamic imports. This includes type definitions for `VMOptions` and `VMContext` to allow for flexible context extension.
* Exported `EdgeVM`, `VM`, and related types (`EdgeVMOptions`, `EdgeContext`, `VMOptions`, `VMContext`) in `lib/env/edge-vm/index.ts` for external usage.
* Added `DispatchFetch`, `RejectionHandler`, and `ErrorHandler` …
> feat: adding support for dynamic import to the runtime environment

- .github/dependabot.yml
- .github/workflows/osv-scanner-pr.yml
- CHANGELOG.md
- package.json
- tests/e2e/simple-js-network-list-with-firewall.test.js
- tests/e2e/simple-js-network-list.test.js
- yarn.lock
This pull request introduces several improvements to automation and dependency management, along with a minor bug fix and version bump for the `edge-functions` package. The most significant changes include the addition of configuration files for Dependabot and OSV-Scanner, as well as updates to the `azion` library version.
**Automation and Dependency Management:**
* Added `.github/dependabot.yml` to enable automated dependency updates for both npm packages and GitHub Actions, with custom grouping and commit message strategies.
* Added `.github/workflows/osv-scanner-pr.yml` to automate vulnerability scanning of pull requests using OSV-Scanner, improving security practices.
**Version and Dependency Updates:**
* Updated `package.json` to bump the package version to `6.1.2-stage.1`, …
> Release 6.1.2
